### ISSUE TITLE
Heating

### ISSUE THREAD

**Issue by jaqpot** [lostcontrol/poupool#1]
# Poolex Triline Premium 22kW
## Heater configuration
- on/off control with external relay (remove jumper on terminal "ON/OFF")
- always on, temperature setpoint to 30°C 
- additional setting to be defined

### RPi
- Heating is started by setting RPi GPIO24 high
- Heating is stopped by setting RPi GPIO24 low

### openHAB
- temperature setpoint selection on 1st page
- current temperature on 1st page
- status of heater on 1st page
- Force on (or Boost) with minimal duration x min, maximal duration x min defined in PAC parameters tab
- Temperature regulation on/off in PAC parameters tab
- When started, the heater should remains on for a minimal duration of X min (limit the number of on/off cycles)
- 1 heating cycle per day maximum (but force/boost always allowed)
- heating cycle start by default at a defined time in the PAC parameter tab.

**Comment by lostcontrol** [comment]
Several questions:
- I guess we control the temperature with an on/off strategy so we need hysteresis. Do you want this to be configurable?
- When to start the daily heating cycle? Only one cycle per day? Really?
- Does the heating have priority over filtration? Meaning we do start the pump as soon as heating is required or do we delay the heating? Also any requirements on the pump speed when the heating runs?

**Comment by lostcontrol** [comment]
The boost feature is missing but let's first test a bit what we have. That should already cover most use cases.
