### ISSUE TITLE
Another raspberry pi swimming-pool automation project.

### ISSUE THREAD

**Issue by segalion** [lostcontrol/poupool#26]
Please checkout raspipool (https://github.com/segalion/raspipool)
and (wip) very visual wiki in https://github.com/segalion/raspipool/wiki

**Comment by stritti** [comment]
I added it to my list too: https://github.com/smart-swimmingpool/smart-swimmingpool/wiki/Ressources
Interesting project!

**Comment by lostcontrol** [comment]
@segalion this is an issue tracking system, not a advertisement platform. Thank you.
