### ISSUE TITLE
Wintering state required?

### ISSUE THREAD

**Issue by lostcontrol** [lostcontrol/poupool#5]
Do we still need the wintering state/feature or do you think we can remove it? That would simplify the code a bit so if you don't need it, better remove it.

**Comment by jaqpot** [comment]
If a wintering can be done by adjusting the parameters of the standard mode (Heater off, pool desinfection low, filtration low, eco mode only...), we can remove it.
I will most probably always emty the overflow bassin during winter....
It is still required to start the NCC for 5min if the NCC trap is <0°C

**Comment by lostcontrol** [comment]
Ok, well, maybe it is better then to have a wintering mode which actually lower/set all those settings. Much easier than having to touch many different parameters. It is in currently so should not be a big deal to keep it and improve it a bit.

**Comment by lostcontrol** [comment]
Closing since the current wintering mode works and is required.
